In [13]:
# General Data Handling
import numpy as np
import xarray as xr
from datetime import datetime

# xclim
import xclim as xclim

# Handling Warnings
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

# Importing files from directory
from glob import glob

# Plotting
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
%matplotlib inline
import cartopy.crs as ccrs
import cartopy.feature as cfeature

In [2]:
# GCM:EC-EARTH RCM:SMHI Temperature Data Historical
# read in temperature data
ICHEC_historic_temp = '/scratch3/climriskdata/EUR-11N/ICHEC-EC-EARTH_SMHI-RCA4_v1/historical/tas/reduced_tas_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-19751231_LL.nc'
# load the data by using open_dataset function of xarray
ds_temp_historic = xr.open_dataset(ICHEC_historic_temp)
ds_temp_historic

<xarray.Dataset>
Dimensions:    (time: 1826, bnds: 2, lon: 61, lat: 41)
Coordinates:
  * time       (time) datetime64[ns] 1971-01-01T12:00:00 ... 1975-12-31T12:00:00
  * lon        (lon) float64 5.0 5.1 5.2 5.3 5.4 ... 10.6 10.7 10.8 10.9 11.0
  * lat        (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 47.7 47.8 47.9 48.0
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] ...
    tas        (time, lat, lon) float32 ...
Attributes: (12/25)
    CDI:                            Climate Data Interface version ?? (http:/...
    history:                        Fri Mar 13 11:11:49 2020: cdo sellonlatbo...
    institution:                    Swedish Meteorological and Hydrological I...
    Conventions:                    CF-1.4
    contact:                        rossby.cordex@smhi.se
    creation_date:                  2013-06-21-T00:12:54Z
    ...                             ...
    references:                     http://www.smhi.se/en/Research/Research-d...
    tracking_id:                    fccbdda2-e3c9-4c0c-9cd8-8f7b2417c8da
    rossby_comment:                 201137: CORDEX Europe 0.11 deg | RCA4 v1 ...
    rossby_run_id:                  201137
    rossby_grib_path:               /nobackup/rossby16/rossby/joint_exp/corde...
    CDO:                            Climate Data Operators version 1.9.3 (htt...

In [4]:
### Transform to Data Array
ds_temp_historic = ds_temp_historic['tas']
print(ds_temp_historic)

<xarray.DataArray 'tas' (time: 1826, lat: 41, lon: 61)>
[4566826 values with dtype=float32]
Coordinates:
  * time     (time) datetime64[ns] 1971-01-01T12:00:00 ... 1975-12-31T12:00:00
  * lon      (lon) float64 5.0 5.1 5.2 5.3 5.4 5.5 ... 10.6 10.7 10.8 10.9 11.0
  * lat      (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 47.6 47.7 47.8 47.9 48.0
Attributes:
    standard_name:  air_temperature
    long_name:      Near-Surface Air Temperature
    units:          K
    cell_methods:   time: mean


In [6]:
#### Calculate GSS and GSE
#Growing Season End: Day of the year of the start of a sequence of days with mean daily temperatures consistently above or equal to a given threshold (default: 5℃).
from xclim.indices import growing_season_end
gse_historic = growing_season_end(tas=ds_temp_historic, thresh='5.0 degC', mid_date='07-01', window=1, freq='YS')
gse_historic

#Growing Season Start: Day of the year of the start of a sequence of days with mean daily temperatures consistently above or equal to a given threshold (default: 5℃).
from xclim.indices import growing_season_start
gss_historic = growing_season_start(tas=ds_temp_historic)
gss_historic

<xarray.DataArray 'dayofyear' (time: 5, lat: 41, lon: 61)>
array([[[ 32.,  49.,  50., ...,  51.,  51.,  51.],
        [ 49.,  50.,  50., ..., 113.,  73.,  73.],
        [ 49.,  50.,  50., ...,  73.,  73.,  73.],
        ...,
        [ 71.,  72.,  72., ..., 118., 118., 118.],
        [ 71.,  71.,  72., ..., 104.,  72.,  72.],
        [ 71.,  71.,  71., ...,  91.,  72.,  72.]],

       [[ 31.,  31.,  31., ...,  43.,  43.,  43.],
        [ 31.,  31.,  40., ...,  55.,  55.,  44.],
        [ 31.,  31.,  41., ..., 104.,  54.,  53.],
        ...,
        [ 31.,  31.,  94., ..., 103.,  94.,  94.],
        [  3.,   3.,  31., ...,  94.,  94.,  94.],
        [  3.,   3.,  31., ...,  94.,  94.,  94.]],

       [[ 13.,  13.,  13., ...,  37.,  37.,  37.],
        [ 13.,  13.,  13., ...,  40.,  40.,  40.],
        [ 13.,  13.,  40., ...,  40.,  37.,  37.],
        ...,
        [ 46.,  46.,  46., ...,  96.,  96.,  96.],
        [ 46.,  46.,  46., ...,  96.,  96.,  96.],
        [ 46.,  46.,  46., ...,  96.,  96.,  96.]],

       [[ 37.,  62.,  63., ...,  64.,  64.,  64.],
        [ 37.,  63.,  63., ..., 101., 100., 100.],
        [ 62.,  63.,  63., ..., 101., 100.,  94.],
        ...,
        [ 63.,  63.,  63., ..., 101., 101.,  69.],
        [ 63.,  63.,  63., ..., 101.,  69.,  69.],
        [ 63.,  63.,  63., ...,  69.,  69.,  69.]],

       [[ 34.,  34.,  34., ...,  78.,  78.,  78.],
        [ 34.,  34.,  34., ...,  86.,  85.,  84.],
        [ 34.,  34.,  34., ...,  85.,  85.,  77.],
        ...,
        [ 52.,  52.,  52., ...,  91.,  91.,  85.],
        [ 51.,  52.,  52., ...,  85.,  85.,  85.],
        [ 51.,  51.,  52., ...,  85.,  85.,  85.]]])
Coordinates:
  * lon      (lon) float64 5.0 5.1 5.2 5.3 5.4 5.5 ... 10.6 10.7 10.8 10.9 11.0
  * lat      (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 47.6 47.7 47.8 47.9 48.0
  * time     (time) datetime64[ns] 1971-01-01 1972-01-01 ... 1975-01-01
Attributes:
    units:         
    is_dayofyear:  1
    calendar:      default

In [10]:
# read in precipitation data from GCM:EC-EARTH RCM:SMHI Precipitation Data Historical
ICHEC_historic_pr = '/scratch3/climriskdata/EUR-11N/ICHEC-EC-EARTH_SMHI-RCA4_v1/historical/pr/reduced_pr_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-19751231_LL.nc'
ds_pr_historic = xr.open_dataset(ICHEC_historic_pr)
ds_pr_historic

<xarray.Dataset>
Dimensions:    (time: 1826, bnds: 2, lon: 61, lat: 41)
Coordinates:
  * time       (time) datetime64[ns] 1971-01-01T12:00:00 ... 1975-12-31T12:00:00
  * lon        (lon) float64 5.0 5.1 5.2 5.3 5.4 ... 10.6 10.7 10.8 10.9 11.0
  * lat        (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 47.7 47.8 47.9 48.0
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] ...
    pr         (time, lat, lon) float32 ...
Attributes: (12/25)
    CDI:                            Climate Data Interface version ?? (http:/...
    history:                        Fri Mar 13 11:11:39 2020: cdo sellonlatbo...
    institution:                    Swedish Meteorological and Hydrological I...
    Conventions:                    CF-1.4
    contact:                        rossby.cordex@smhi.se
    creation_date:                  2013-06-21-T03:34:44Z
    ...                             ...
    references:                     http://www.smhi.se/en/Research/Research-d...
    tracking_id:                    f299a24d-63ba-4f8d-a81d-0621be5b7ea5
    rossby_comment:                 201137: CORDEX Europe 0.11 deg | RCA4 v1 ...
    rossby_run_id:                  201137
    rossby_grib_path:               /nobackup/rossby16/rossby/joint_exp/corde...
    CDO:                            Climate Data Operators version 1.9.3 (htt...

In [61]:
# Define the latitude and longitude ranges for Northern Africa and the Mediterranean
lat_range = slice(30, 45)
lon_range = slice(-10, 25)

# Function to slice the dataset
def slice_dataset(ds, lat_range, lon_range):
    return ds.sel(lat=lat_range, lon=lon_range)
ds_pr_historic_sliced = slice_dataset(ds_pr_historic, lat_range, lon_range)

In [62]:
# Turn dates to day of year
ds_pr_historic_sliced['time'] = ds_pr_historic['time']
day_of_year_historic = ds_pr_historic_sliced['time'].dt.dayofyear
ds_pr_historic_sliced['time'] = day_of_year_historic
print(ds_pr_historic_sliced)

<xarray.Dataset>
Dimensions:    (time: 1826, bnds: 2, lon: 61, lat: 11)
Coordinates:
  * time       (time) int64 1 2 3 4 5 6 7 8 ... 358 359 360 361 362 363 364 365
  * lon        (lon) float64 5.0 5.1 5.2 5.3 5.4 ... 10.6 10.7 10.8 10.9 11.0
  * lat        (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 44.7 44.8 44.9 45.0
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] ...
    pr         (time, lat, lon) float32 ...
Attributes: (12/25)
    CDI:                            Climate Data Interface version ?? (http:/...
    history:                        Fri Mar 13 11:11:39 2020: cdo sellonlatbo...
    institution:                    Swedish Meteorological and Hydrological I...
    Conventions:                    CF-1.4
    contact:                        rossby.cordex@smhi.se
    creation_date:                  2013-06-21-T03:34:44Z
    ...                             ...
    references:                     http://www.smhi.se/en/Research/Resear

In [105]:
# Iterate over each year
for year in range(1971, 1975):
    # Get the end of the growing season for the current year
    end_of_growing_season = gse_historic.sel(time=f'{year}-01-01').squeeze()
    
    # Create a mask to select days before the end of the growing season for the current year
    mask = ds_pr_historic_sliced.time <= end_of_growing_season
    
    # Apply the mask to subset the dataset for the current year
    subset_gse_historic = ds_pr_historic_sliced.where(mask, drop=True)

In [106]:
# Iterate over each year
for year in range(1971, 1975):
    # Get the end of the growing season for the current year
    start_of_growing_season = gss_historic.sel(time=f'{year}-01-01').squeeze()
    
    # Create a mask to select days before the end of the growing season for the current year
    mask = subset_gse_historic.time >= start_of_growing_season
    
    # Apply the mask to subset the dataset for the current year
    subset_gss_gse_historic = subset_gse_historic.where(mask, drop=True)

In [99]:
subset_gss_gse_historic_copy = subset_gss_gse_historic.copy()

In [100]:
subset_gss_gse_historic_copy

<xarray.Dataset>
Dimensions:    (time: 1825, bnds: 2, lat: 11, lon: 61)
Coordinates:
  * time       (time) int64 1 2 3 4 5 6 7 8 ... 358 359 360 361 362 363 364 365
  * lon        (lon) float64 5.0 5.1 5.2 5.3 5.4 ... 10.6 10.7 10.8 10.9 11.0
  * lat        (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 44.7 44.8 44.9 45.0
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds, lat, lon) datetime64[ns] NaT NaT NaT ... NaT NaT NaT
    pr         (time, lat, lon) float32 nan nan nan nan nan ... nan nan nan nan
Attributes: (12/25)
    CDI:                            Climate Data Interface version ?? (http:/...
    history:                        Fri Mar 13 11:11:39 2020: cdo sellonlatbo...
    institution:                    Swedish Meteorological and Hydrological I...
    Conventions:                    CF-1.4
    contact:                        rossby.cordex@smhi.se
    creation_date:                  2013-06-21-T03:34:44Z
    ...                             ...
    references:                     http://www.smhi.se/en/Research/Research-d...
    tracking_id:                    f299a24d-63ba-4f8d-a81d-0621be5b7ea5
    rossby_comment:                 201137: CORDEX Europe 0.11 deg | RCA4 v1 ...
    rossby_run_id:                  201137
    rossby_grib_path:               /nobackup/rossby16/rossby/joint_exp/corde...
    CDO:                            Climate Data Operators version 1.9.3 (htt...

In [107]:
import xarray as xr

# Assume 'original_years' is a list or array of years corresponding to your dataset
start_year = 1971
end_year = 1975

# Generate a range of dates covering the specified years
dates = xr.cftime_range(start=f"{start_year}-01-01", end=f"{end_year}-12-31", freq="D", calendar="noleap")

# Extract the year component from the dates
years = dates.year

# Assign the new 'time' coordinate to the dataset
subset_gss_gse_historic_copy['time'] = ('time', dates)

# Verify the result
print(subset_gss_gse_historic_copy['time'])

TypeError: Cannot convert input [1971-01-01 00:00:00] of type <class 'cftime._cftime.DatetimeNoLeap'> to Timestamp

In [102]:
### Transform to Data Array
subset_gss_gse_historic_copy = subset_gss_gse_historic_copy['pr']
subset_gss_gse_historic_copy

<xarray.DataArray 'pr' (time: 1825, lat: 11, lon: 61)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) object 1971-01-01 00:00:00 ... 1975-12-31 00:00:00
  * lon      (lon) float64 5.0 5.1 5.2 5.3 5.4 5.5 ... 10.6 10.7 10.8 10.9 11.0
  * lat      (lat) float64 44.0 44.1 44.2 44.3 44.4 ... 44.6 44.7 44.8 44.9 45.0
Attributes:
    standard_name:  precipitation_flux
    long_name:      Precipitation
    units:          kg m-2 s-1
    cell_methods:   time: mean

In [113]:
import pandas as pd

# Extract time values and convert to Pandas DataFrame
time_df = pd.DataFrame(subset_gss_gse_historic_copy['time'].values, columns=['time'])

# Configure Pandas to display all rows
pd.set_option('display.max_rows', None)

# Display the DataFrame
print(time_df)


                     time
0     1971-01-01 00:00:00
1     1971-01-02 00:00:00
2     1971-01-03 00:00:00
3     1971-01-04 00:00:00
4     1971-01-05 00:00:00
5     1971-01-06 00:00:00
6     1971-01-07 00:00:00
7     1971-01-08 00:00:00
8     1971-01-09 00:00:00
9     1971-01-10 00:00:00
10    1971-01-11 00:00:00
11    1971-01-12 00:00:00
12    1971-01-13 00:00:00
13    1971-01-14 00:00:00
14    1971-01-15 00:00:00
15    1971-01-16 00:00:00
16    1971-01-17 00:00:00
17    1971-01-18 00:00:00
18    1971-01-19 00:00:00
19    1971-01-20 00:00:00
20    1971-01-21 00:00:00
21    1971-01-22 00:00:00
22    1971-01-23 00:00:00
23    1971-01-24 00:00:00
24    1971-01-25 00:00:00
25    1971-01-26 00:00:00
26    1971-01-27 00:00:00
27    1971-01-28 00:00:00
28    1971-01-29 00:00:00
29    1971-01-30 00:00:00
30    1971-01-31 00:00:00
31    1971-02-01 00:00:00
32    1971-02-02 00:00:00
33    1971-02-03 00:00:00
34    1971-02-04 00:00:00
35    1971-02-05 00:00:00
36    1971-02-06 00:00:00
37    1971-0

In [112]:
# Calculate dry days
dry_days_historic = dry_days(subset_gss_gse_historic_copy, thresh='2 mm/d', freq='YS', op='<')

# Print result
print(dry_days_historic)

<xarray.DataArray 'pr' (time: 5, lat: 11, lon: 61)>
array([[[253, 188, 173, ..., 163, 165, 170],
        [248, 189, 166, ..., 128, 137, 144],
        [219, 180, 155, ..., 135, 147, 156],
        ...,
        [178, 151, 139, ..., 180, 178, 179],
        [176, 153, 113, ..., 182, 182, 185],
        [180, 171, 156, ..., 187, 190, 188]],

       [[251, 192, 176, ..., 163, 162, 170],
        [247, 187, 170, ..., 127, 130, 135],
        [220, 177, 157, ..., 126, 145, 167],
        ...,
        [163, 144, 124, ..., 185, 185, 186],
        [158, 142, 109, ..., 185, 184, 187],
        [165, 154, 147, ..., 185, 184, 186]],

       [[244, 193, 179, ..., 174, 175, 180],
        [242, 190, 170, ..., 135, 137, 144],
        [216, 179, 155, ..., 141, 151, 165],
        ...,
        [172, 152, 142, ..., 196, 199, 196],
        [173, 153, 110, ..., 198, 200, 199],
        [181, 176, 159, ..., 195, 197, 199]],

       [[235, 173, 152, ..., 140, 143, 149],
        [227, 167, 149, ..., 103, 104, 111],
   

In [110]:
from xclim.indices import dry_spell_frequency
import xarray as xr
import pandas as pd
from xclim.indices import dry_days

# Calculate dry days
dry_spells_frequency_historic = dry_spell_frequency(subset_gss_gse_historic_copy, thresh='2.0 mm', window=5, freq='YS', resample_before_rl=True, op='sum')
# Print result
print(dry_spells_frequency_historic)

<xarray.DataArray 'pr' (time: 5, lat: 11, lon: 61)>
array([[[18, 12, 14, ..., 14, 12, 13],
        [16, 12, 15, ..., 13, 12, 11],
        [15, 10,  9, ..., 10, 12,  9],
        ...,
        [12,  9, 11, ..., 17, 16, 16],
        [10,  9,  6, ..., 17, 15, 15],
        [11,  8,  7, ..., 17, 16, 16]],

       [[16, 11, 14, ..., 11, 13, 12],
        [17, 11, 16, ..., 10, 10, 10],
        [15, 14, 14, ...,  9, 10, 11],
        ...,
        [11, 10,  9, ..., 15, 15, 14],
        [11, 10,  8, ..., 14, 13, 13],
        [12,  9, 11, ..., 13, 13, 13]],

       [[16, 15, 16, ..., 10, 10, 11],
        [19, 17, 15, ...,  8,  7,  7],
        [16, 15, 14, ...,  8,  9,  9],
        ...,
        [15, 13, 12, ..., 13, 15, 14],
        [13, 13,  7, ..., 14, 15, 14],
        [11, 13, 14, ..., 12, 14, 15]],

       [[20, 15, 13, ...,  9, 10, 11],
        [19, 15,  9, ...,  7,  7,  7],
        [15, 12,  8, ...,  7,  8, 10],
        ...,
        [11,  7,  7, ..., 12, 12, 15],
        [12,  7,  6, ..., 13, 12